package aplication.interfaces;

public enum TipoMenu {
	INICIAR_SISTEMA, CADASTRO, LOGIN, INICIO, GERAL, EDICAO_ORIENTACAO, ADICAO_ORIENTACAO, PESQUISA_ORIENTACAO,
	EXIBIR_ORIENTACOES, FIM, FALHA, CERTO, FILTRO_GERAL, MOSTRAR_ORIENTACAO, ALTERAR_IDIOMA, DEFINIR_FILTRO,
	VISUALIZAR_FILTRO, APAGAR_ORIENTACAO, HISTORICO_COMANDOS;

}
