package service.commandos;

public enum TiposComando {
	ADICIONAR_ORIENTACAO, REMOVER_ORIENTACAO, EDITAR_ORIENTACAO, DESFAZER_ADICAO_ORIENTACAO,
	DESFAZER_REMOCAO_ORIENTACAO, DESFAZER_EDICAO_REMOCAO;
}
